name: Deploy Develop

on:
  push:
    branches:
      - develop
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: Fooji/create-aws-profile-action@v1
      with:
        profile: guardian-dev
        region: us-east-2
        key: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
        secret: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
    - run: npm ci
    - run: npm run deploy:dev
